name: Daily Scrape and Publish

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2 --no-install-recommends
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper_flask/requirements.txt

      - name: Run scraper
        env:
          PIP_NO_CACHE_DIR: 'off'
        run: |
          python scraper_flask/scripts/run_scraper.py

      - name: Commit generated JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'scraper_flask/data/hackathons.json'
          commit_message: 'chore: update hackathons.json [skip ci]'
          branch: 'main'
          # use action inputs accepted by this action
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          # avoid fetching extra refs (we already checked out)
          skip_fetch: true
